# Generated by Django 3.2.13 on 2022-11-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_path',
            field=models.TextField(null=True),
        ),
    ]
