# Generated by Django 3.2.13 on 2022-11-17 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='wish_user',
            field=models.ManyToManyField(blank=True, related_name='wish_movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
