# Generated by Django 3.2.13 on 2022-11-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_wish_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_ids',
            new_name='genres',
        ),
    ]
