# Generated by Django 3.2.13 on 2022-11-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_wish_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wish_movie',
        ),
    ]
