# Generated by Django 3.2.13 on 2022-11-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_genres_movie_genre_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_ids',
            new_name='genres',
        ),
    ]
