# Generated by Django 3.2.13 on 2022-11-20 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_rename_genre_ids_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='like_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
